command:
  - jupiter nbconvert  --to html --output /output/mnist.html --execute /code/mnist.ipynb --ExecutePreprocessor.allow_errors=True --ExecutePreprocessor.timeout=-1

org: missinglinkdemo
project: 5647386479165440
git_repo: git@github.com:missinglinkai/mnist_jupiter.git
